tcp:
  ip: "127.0.0.1"
  tcp_port: 5001

rtu:
  port: "COM3"
  csv_file: "./Interfacing Overview - Export.csv"
  stopbits: 1
  bytesize: 8
  parity: "N"
  baudrate: 38400
  slave_id: 1

MAX_ATTEMPTS: 5
RETRY_DELAY: 1
PATH_TO_DB: "./runs.db"
